version: "3.8"
services:
    jupyter:
        build: .
        ports:
            - 8888:8888


    db:
        image: postgres
        container_name: local_pgdb # psycopg2 (host)
        restart: always
        ports:
            - "5432:5432" # psycopg2(port)
        environment:
            POSTGRES_USER: <Your_user> # psycopg2 (host)
            POSTGRES_PASSWORD: <Your_Password_postgres> # psycopg2 (password)
        volumes:
            - local_pgdata:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin4_container
        restart: always
        ports:
           - "80:80"
        environment:
           PGADMIN_DEFAULT_EMAIL: <Your_email_PGADMIN>
           PGADMIN_DEFAULT_PASSWORD: <Your_Password_PGADMIN>
        volumes:
           - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: